---
- name: Add apt gpg key
  apt_key:
    url: '{{ deconz_gpg_url }}'
    validate_certs: true
    id: '{{ deconz_gpg_id }}'

- name: Add apt repository
  apt_repository:
    repo: '{{ deconz_repo_url_full }}'
    update_cache: true
    filename: deconz.list